import Head from "next/head";
// import styles from "@/styles/Home.module.css";
import List from "@/components/List/List";
import books from "@/mocks/data";
import { Books } from "@/components/interfaces/Book";

export default function Home({books}: {books: Books}) {

  return (
    <>
      <Head>
        <title>List of the Book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        <List books={books}/>
      
      </main>
    </>
  );
}

export async function getServerSideProps(){
  return {
    props: {books},
  }
}
