import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
          </p>
          <div>
          </div>
        </div>

        <div className={styles.center}>
          
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className="flex border-2 border-l-purple-200">
          <div className="flex-none w-32"><h1>01</h1></div>
          <div className="flex-initial w-32 ...">02</div>
          <div className="flex-initial w-32 ...">03</div>
        </div>
      </main>
    </>
  );
}
